# -*- coding: utf-8 -*-
"""ASKCOCO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A_xnq2Wr9J-IE21AAx4kWREJ8w1_j7hJ
"""

# ==========================================
# CELL 1: INSTALL DEPENDENCIES (Clean Version)
# ==========================================
import warnings
warnings.filterwarnings('ignore')

!pip install -q chromadb sentence-transformers openai --no-deps 2>/dev/null
!pip install -q chromadb sentence-transformers openai 2>/dev/null

print("✅ All dependencies installed!")
print("   - openai (for API calls)")
print("   - chromadb (vector memory)")
print("   - sentence-transformers (embeddings)")
print("\n💡 Note: Dependency warnings from Colab's pre-installed packages can be ignored.")

# ==========================================
# CELL 2: SETUP GROQ API KEY (FIXED)
# ==========================================
import os
import sys
from openai import OpenAI
from google.colab import userdata

print("🔑 Setting up Groq API key...")

# --- GET GROQ API KEY ---
# Force the use of Colab Secrets (no hardcoded fallback!)
try:
    GROQ_API_KEY = userdata.get('GROQ_API_KEY')
    if not GROQ_API_KEY:
        raise ValueError("Key not found in secrets")
    print("✅ Groq API key loaded from Colab Secrets")
except Exception as e:
    print("❌ ERROR: Could not load GROQ_API_KEY from Colab Secrets.")
    print("   Please do the following:")
    print("   1. Click the 🔑 'Secrets' icon on the left sidebar.")
    print("   2. Click 'Add new secret'.")
    print("   3. Name it 'GROQ_API_KEY' and paste your Groq API key.")
    print("   4. Turn the toggle ON so the notebook can read it.")
    print("   5. Restart the runtime (Runtime > Restart runtime) and run all cells again.")
    sys.exit(1)

# Initialize Groq client
try:
    client = OpenAI(
        api_key=GROQ_API_KEY,
        base_url="https://api.groq.com/openai/v1"  # Groq's endpoint
    )
    print("✅ Groq client initialized!")
except Exception as e:
    print(f"❌ Failed to initialize Groq client: {e}")
    sys.exit(1)

print("✅ Setup complete!")
print("   - Using Groq's free tier with Llama 3.3 70B")
print("   - Rate Limit: 30 RPM (free tier)")

# ==========================================
# CELL 3: CHROMADB MEMORY SYSTEM
# ==========================================
import chromadb
from chromadb.utils import embedding_functions

print("🔄 Initializing Memory System...")

# Initialize embedding function (runs on CPU, free)
try:
    embedding_function = embedding_functions.SentenceTransformerEmbeddingFunction(
        model_name="all-MiniLM-L6-v2"
    )
    print("✅ Embedding function loaded!")
except Exception as e:
    print(f"⚠️ Failed to load embedding function: {e}")
    embedding_function = None

# Initialize ChromaDB
chroma_client = chromadb.PersistentClient(path="/content/corporate_brain_memory")

# Get or create collection
try:
    if embedding_function:
        collection = chroma_client.get_or_create_collection(
            name="meeting_memory",
            embedding_function=embedding_function
        )
    else:
        collection = chroma_client.get_or_create_collection(
            name="meeting_memory"
        )
    print(f"✅ ChromaDB initialized! {collection.count()} snippets stored")
except Exception as e:
    print(f"❌ Failed to initialize ChromaDB: {e}")
    raise

print("✅ Memory system ready!")

# ==========================================
# CELL 4: LOAD MEETING DATA (FIXED)
# ==========================================
import json
from google.colab import files

# --- UPLOAD YOUR JSON FILE ---
print("📁 Please upload your 'corporate_brain_output.json' file:")
print("   (This is the output from your Deepgram + Gemini pipeline)")

uploaded = files.upload()

if not uploaded:
    print("❌ No file uploaded. Please upload the JSON file.")
    raise FileNotFoundError("No file uploaded")

json_filename = list(uploaded.keys())[0]
print(f"✅ Uploaded: {json_filename}")

# --- LOAD AND PARSE JSON ---
with open(json_filename, 'r') as f:
    data = json.load(f)

print("📊 JSON Structure Detected:")
print(f"   Keys: {list(data.keys())}")

# --- EXTRACT TRANSCRIPT (Supports both formats) ---
transcript_raw = data.get("transcript", [])
transcript_text = ""

# Case 1: transcript is a LIST of objects (your format)
if isinstance(transcript_raw, list):
    print("📝 Transcript format: List of objects")
    snippets = []
    for item in transcript_raw:
        timestamp = item.get("timestamp", "00:00:00")
        speaker = item.get("speaker", "Unknown")
        text = item.get("text", "")
        full_line = f"[{timestamp}] {speaker}: {text}"
        snippets.append({
            "timestamp": timestamp,
            "speaker": speaker,
            "text": text,
            "full_line": full_line
        })
        transcript_text += full_line + "\n"

# Case 2: transcript is a STRING
elif isinstance(transcript_raw, str):
    print("📝 Transcript format: String")
    transcript_text = transcript_raw
    lines = transcript_text.strip().split('\n')
    snippets = []
    for line in lines:
        if not line.strip():
            continue
        try:
            timestamp = line.split(']')[0].replace('[', '').strip()
            rest = line.split(']')[1].strip()
            if ': ' in rest:
                speaker, text = rest.split(': ', 1)
            else:
                speaker, text = "Unknown", rest
            snippets.append({
                "timestamp": timestamp,
                "speaker": speaker,
                "text": text,
                "full_line": line
            })
        except:
            snippets.append({
                "timestamp": "00:00:00",
                "speaker": "Unknown",
                "text": line,
                "full_line": line
            })

else:
    print("❌ Unknown transcript format")
    raise ValueError("Transcript format not supported")

print(f"✅ Parsed {len(snippets)} snippets")

# --- EXTRACT DECISIONS, ACTION ITEMS, PARTICIPANTS ---
# Check both top-level and nested inside 'analysis'
decisions = data.get("decisions", [])
if not decisions and "analysis" in data:
    decisions = data["analysis"].get("decisions", [])

action_items = data.get("action_items", [])
if not action_items and "analysis" in data:
    action_items = data["analysis"].get("action_items", [])

participants = data.get("participants", [])
if not participants and "analysis" in data:
    participants = data["analysis"].get("participants", [])

# Also check speaker_map for participants if not found
if not participants and "speaker_map" in data:
    # Get unique names from speaker_map
    speaker_map = data.get("speaker_map", {})
    participants = list(set(speaker_map.values()))
    # Filter out generic names
    participants = [p for p in participants if p and "Unknown" not in p]

print(f"\n📊 Extracted Data:")
print(f"   - {len(decisions)} decisions")
print(f"   - {len(action_items)} action items")
print(f"   - {len(participants)} participants")

# --- STORE IN CHROMADB ---
# Clear existing memory if any
if collection.count() > 0:
    print(f"⚠️ Memory already has {collection.count()} snippets.")
    overwrite = input("Do you want to clear and reload? (y/n): ").strip().lower()
    if overwrite == 'y':
        chroma_client.delete_collection("meeting_memory")
        collection = chroma_client.get_or_create_collection(
            name="meeting_memory",
            embedding_function=embedding_function
        )
        print("🗑️ Memory cleared.")
    else:
        print("✅ Keeping existing memory. Skipping load.")
        if collection.count() > 0:
            print(f"✅ Memory already has {collection.count()} snippets. Ready to chat!")
            snippets = []  # Prevent re-adding

# Add snippets to memory
if snippets and collection.count() == 0:
    ids = []
    documents = []
    metadatas = []

    for idx, snippet in enumerate(snippets):
        doc_id = f"meeting_001_{idx:04d}"
        ids.append(doc_id)
        documents.append(snippet["full_line"])
        metadatas.append({
            "timestamp": snippet["timestamp"],
            "speaker": snippet["speaker"],
            "source": "Meeting",
            "full_text": snippet["text"]
        })

    collection.add(
        ids=ids,
        documents=documents,
        metadatas=metadatas
    )
    print(f"✅ Added {len(ids)} snippets to memory!")
else:
    if collection.count() > 0:
        print(f"✅ Memory already has {collection.count()} snippets. Skipping add.")

# --- STORE DECISIONS AND ACTION ITEMS FOR CONTEXT ---
# Store as a separate document in ChromaDB so they can be searched
if decisions or action_items:
    # Create a summary document with all decisions and action items
    summary_lines = []
    summary_lines.append("📋 MEETING SUMMARY:")

    if participants:
        summary_lines.append(f"\n👥 Participants: {', '.join(participants)}")

    if decisions:
        summary_lines.append(f"\n📝 Decisions ({len(decisions)}):")
        for i, d in enumerate(decisions, 1):
            summary_lines.append(f"   {i}. {d.get('text', '')} (Confidence: {d.get('confidence', 'unknown')}, Speaker: {d.get('speaker', 'Unknown')})")

    if action_items:
        summary_lines.append(f"\n✅ Action Items ({len(action_items)}):")
        for i, a in enumerate(action_items, 1):
            assignee = a.get('assignee', 'Unassigned')
            deadline = a.get('deadline', 'No deadline')
            summary_lines.append(f"   {i}. {a.get('task', '')} (Assignee: {assignee}, Deadline: {deadline})")

    summary_text = "\n".join(summary_lines)

    # Add to ChromaDB as a single document
    summary_id = "meeting_summary_0000"
    collection.add(
        ids=[summary_id],
        documents=[summary_text],
        metadatas=[{
            "timestamp": "00:00:00",
            "speaker": "System",
            "source": "Meeting Summary",
            "full_text": summary_text,
            "is_summary": "true"
        }]
    )
    print(f"✅ Added meeting summary with decisions and action items to memory!")

print("\n📊 Memory Summary:")
print(f"   - {collection.count()} total snippets")
print(f"   - {len(decisions)} decisions extracted")
print(f"   - {len(action_items)} action items extracted")
print(f"   - {len(participants)} participants detected")

print("\n✅ Meeting data loaded successfully!")

# ==========================================
# CELL 5: ASK COCO ENGINE (Clean Citations)
# ==========================================
import time
import re

# --- EXPANDED MEETING KEYWORDS ---
MEETING_KEYWORDS = [
    # Meeting-related terms
    'meeting', 'meetings', 'discuss', 'discussed', 'discussion', 'agenda',
    'decision', 'decisions', 'decide', 'decided', 'resolved', 'approved',
    'action item', 'action items', 'task', 'tasks', 'assign', 'assigned',
    'deadline', 'deadlines', 'timeline', 'timelines', 'schedule',
    # ACTION WORDS
    'summarize', 'summarized', 'summary', 'explain', 'explained',
    'describe', 'described', 'detail', 'details', 'overview',
    'list', 'lists', 'listed', 'mention', 'mentioned',
    'tell', 'told', 'say', 'said', 'talk', 'talked', 'speak', 'spoke',
    # Speaker-related terms
    'proposed', 'suggested', 'agreed', 'disagreed', 'asked', 'answered',
    'clarified', 'recommended', 'advised', 'warned', 'noted', 'observed',
    # Content-related terms
    'project', 'project alpha', 'budget', 'vendor', 'provider', 'audit',
    'security', 'compliance', 'policy', 'freeze', 'onboarding',
    # People (from your meeting)
    'samuel', 'alex', 'sarah', 'tom', 'diana', 'speaker',
    # Meeting artifacts
    'transcript', 'transcripts', 'minutes', 'slide', 'slides',
    'presentation', 'presentations', 'notes', 'record', 'recorded',
    # Time-related
    'q1', 'q2', 'q3', 'q4', 'quarter', 'month', 'week', 'today',
    'yesterday', 'tomorrow', 'last week', 'next week',
    # Question starters
    'what', 'who', 'why', 'when', 'where', 'how', 'which', 'whom',
    'whose', 'did', 'does', 'do', 'was', 'were', 'has', 'have',
    'is', 'are', 'will', 'would', 'could', 'should', 'may', 'might',
]

# --- MEETING-RELATED PHRASES ---
MEETING_PHRASES = [
    "tell me", "show me", "give me", "fill me in", "walk me through",
    "let me know", "i want to know", "i need to know", "can you",
    "could you", "would you", "do you know", "did you know",
]

def is_meeting_related(question: str) -> bool:
    """
    Check if a question is likely meeting-related.
    Uses keyword matching and contextual phrases.
    """
    question_lower = question.lower().strip()

    # SPECIAL CASE: Short questions (1-2 words)
    short_meeting_words = [
        'summary', 'summarize', 'overview', 'recap', 'highlights',
        'decisions', 'action', 'actions', 'tasks', 'task',
        'participants', 'speakers', 'attendees', 'people'
    ]
    if question_lower in short_meeting_words:
        return True

    # Check for meeting keywords
    for keyword in MEETING_KEYWORDS:
        if keyword.lower() in question_lower:
            return True

    # Check for meeting-related phrases
    for phrase in MEETING_PHRASES:
        if phrase.lower() in question_lower:
            return True

    # Check for natural language patterns
    question_starters = ['what', 'who', 'why', 'when', 'where', 'how', 'which', 'whom']
    words = question_lower.split()
    if words and words[0] in question_starters:
        if len(words) >= 3:
            return True

    return False

def ask_coco(question, max_snippets=5, retry_count=3):
    """
    Ask Coco a question about your meetings using Groq.
    Returns an answer with citations if the question is meeting-related.
    """

    # --- STEP 0: RELEVANCE PRE-CHECK ---
    if not is_meeting_related(question):
        return {
            "answer": "🤷 I'm Coco, your meeting intelligence assistant. I can only answer questions about your meetings, decisions, action items, and participants. For example, you can ask me:\n\n• 'What decisions were made?'\n• 'What did Samuel say about certificates?'\n• 'Who was assigned to the task?'\n• 'Summarize the meeting'\n\nI don't have information about general topics like weather, news, or non-meeting related questions.",
            "citations": [],  # ✅ Empty citations for non-meeting questions
            "has_answer": False,
            "not_meeting_related": True
        }

    # --- STEP 1: Semantic Search ---
    try:
        results = collection.query(
            query_texts=[question],
            n_results=max_snippets
        )
    except Exception as e:
        return {
            "answer": f"Error searching memory: {e}",
            "citations": [],  # ✅ Empty citations on error
            "has_answer": False,
            "not_meeting_related": False
        }

    # --- STEP 2: Build Context ---
    context_lines = []
    citations = []

    if results['documents'] and results['documents'][0]:
        for i, doc in enumerate(results['documents'][0]):
            metadata = results['metadatas'][0][i] if results['metadatas'] else {}
            timestamp = metadata.get('timestamp', 'Unknown')
            speaker = metadata.get('speaker', 'Unknown')
            context_lines.append(f"[{timestamp}] {speaker}: {doc}")
            citations.append({
                "timestamp": timestamp,
                "speaker": speaker,
                "source": metadata.get('source', 'Meeting')
            })
    else:
        return {
            "answer": "🤷 I couldn't find any relevant information about that in your meeting records. Try asking about specific decisions, speakers, or topics discussed in your meetings.",
            "citations": [],  # ✅ Empty citations when no data found
            "has_answer": False,
            "not_meeting_related": False
        }

    context = "\n".join(context_lines)

    # --- STEP 3: Build Prompt ---
    prompt = f"""
You are Coco, the AI assistant for Corporate Brain. You answer questions based ONLY on the meeting transcripts provided below.

**Context (from processed meetings):**
{context}

**Question:** {question}

**Instructions:**
1. Answer the question using ONLY the information in the context above.
2. If the context doesn't contain the answer, say: "I don't have information about that in my meeting records."
3. If you use specific information, cite the source using the timestamp and speaker.
4. Be concise but informative (2-3 sentences maximum).
5. Never mention that you're an AI or that you're using a transcript.

**Answer:**
"""

    # --- STEP 4: Generate Answer with Groq (with retry) ---
    for attempt in range(retry_count):
        try:
            response = client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=[
                    {"role": "user", "content": prompt}
                ],
                temperature=0.3,
                max_tokens=500
            )

            answer = response.choices[0].message.content.strip()
            if answer.startswith("Answer:"):
                answer = answer[7:].strip()

            print(f"✅ Answer generated successfully using Groq!")

            # --- Post-check: Check if the answer actually contains useful info ---
            if len(answer) < 10 or "don't have information" in answer.lower():
                return {
                    "answer": "🤷 I don't have information about that in my meeting records. Try asking about specific decisions, speakers, or topics discussed in your meetings.",
                    "citations": [],  # ✅ Empty citations when no answer
                    "has_answer": False,
                    "not_meeting_related": False
                }

            # ✅ Only return citations if we have a valid answer
            return {
                "answer": answer,
                "citations": citations,  # ✅ Citations only for valid answers
                "has_answer": True,
                "context": context_lines,
                "not_meeting_related": False
            }

        except Exception as e:
            error_msg = str(e)
            if "429" in error_msg or "rate limit" in error_msg.lower():
                wait_time = (attempt + 1) * 3
                print(f"⚠️ Rate limited. Retrying in {wait_time} seconds... (Attempt {attempt+1}/{retry_count})")
                time.sleep(wait_time)
            else:
                print(f"❌ Groq error: {error_msg}")
                return {
                    "answer": f"Error: {error_msg}",
                    "citations": [],  # ✅ Empty citations on error
                    "has_answer": False,
                    "not_meeting_related": False
                }

    return {
        "answer": "Sorry, I'm having trouble connecting to my brain right now. Please try again in a moment.",
        "citations": [],  # ✅ Empty citations on timeout
        "has_answer": False,
        "not_meeting_related": False
    }

print("✅ Ask Coco engine loaded with Groq!")
print("   - Model: llama-3.3-70b-versatile")
print("   - Rate Limit: 30 RPM (free tier)")
print("   - Relevance detection: Active")
print("   - Citations: Only shown for valid meeting answers")

# ==========================================
# CELL 5.5: DEBUG TEST (Test Relevance)
# ==========================================
print("🔍 Testing relevance detection...")

test_questions = [
    "Summarize",
    "Summary",
    "Decisions",
    "What did Samuel say?",
    "Who is the CEO of Google?",
    "Tell me a joke",
    "S",
]

for q in test_questions:
    result = ask_coco(q)
    print(f"🧑 {q}")
    print(f"🧠 {result['answer'][:100]}...\n")

# ==========================================
# CELL 6: INTERACTIVE CHAT UI (Clean Citations)
# ==========================================
import ipywidgets as widgets
from IPython.display import display, clear_output, HTML

# --- Create widgets ---
question_input = widgets.Textarea(
    value='',
    placeholder='Ask Coco about any meeting, decision, or speaker...\nPress Shift+Enter to submit, or click the button.',
    description='',
    layout=widgets.Layout(width='90%', height='80px')
)

submit_button = widgets.Button(
    description='Ask Coco 🧠',
    button_style='primary',
    layout=widgets.Layout(width='180px')
)

clear_button = widgets.Button(
    description='Clear Chat',
    button_style='warning',
    layout=widgets.Layout(width='130px')
)

output_area = widgets.Output()

# --- Chat history ---
chat_history = []

# --- Display UI ---
display(HTML("<h1>🧠 Ask Coco</h1>"))
display(HTML("<i>Ask natural language questions about your meetings, decisions, and action items.</i>"))
display(HTML("<hr>"))
display(question_input)
display(widgets.HBox([submit_button, clear_button]))
display(output_area)

# --- Submit handler ---
def on_submit(b):
    global chat_history
    question = question_input.value.strip()

    if not question:
        with output_area:
            clear_output()
            print("⚠️ Please enter a question.")
        return

    # Clear input
    question_input.value = ''

    with output_area:
        clear_output(wait=True)

        # Show chat history
        for entry in chat_history:
            print(f"🧑 **You:** {entry['question']}")
            print(f"🧠 **Coco:** {entry['answer']}\n")
            # ✅ Only show citations if they exist
            if entry.get('citations') and len(entry.get('citations', [])) > 0:
                for cite in entry['citations']:
                    print(f"   📎 Source: {cite['source']} at {cite['timestamp']} ({cite['speaker']})")
            print("-" * 50)

        # Get response
        print(f"🧑 **You:** {question}")
        print("🧠 **Coco:** Thinking...")

        # Call ask_coco with debug output
        try:
            result = ask_coco(question)
            answer = result.get("answer", "No response")
            citations = result.get("citations", [])
            not_meeting = result.get("not_meeting_related", False)
        except Exception as e:
            answer = f"❌ Error: {e}"
            citations = []
            not_meeting = False
            print(f"❌ Error in ask_coco: {e}")

        # Display answer
        clear_output(wait=True)

        # Add to chat history
        chat_history.append({
            "question": question,
            "answer": answer,
            "citations": citations,
            "not_meeting": not_meeting
        })

        # Display all chat messages
        for entry in chat_history:
            # Show a special icon for non-meeting questions
            if entry.get('not_meeting', False):
                print(f"🧑 **You:** {entry['question']}")
                print(f"🧠 **Coco:** 🤷 {entry['answer']}\n")
            else:
                print(f"🧑 **You:** {entry['question']}")
                print(f"🧠 **Coco:** {entry['answer']}\n")

            # ✅ Only show citations if they exist
            if entry.get('citations') and len(entry.get('citations', [])) > 0:
                for cite in entry['citations']:
                    print(f"   📎 Source: {cite['source']} at {cite['timestamp']} ({cite['speaker']})")
            print("-" * 50)

# Connect the button
submit_button.on_click(on_submit)

# --- Clear handler ---
def on_clear(b):
    global chat_history
    chat_history = []
    with output_area:
        clear_output()
        print("💬 Chat cleared. Ask a new question!")

clear_button.on_click(on_clear)

# --- Handle keyboard shortcuts ---
def on_keypress(event):
    if event['type'] == 'keydown':
        if (event['keysym'] == 'Return' or event['keysym'] == 'KP_Enter') and (event['shift'] or event['ctrl']):
            submit_button.click()
            return

question_input.on_msg(on_keypress)

print("✅ Chat interface ready!")
print("   - Type your question and click 'Ask Coco 🧠'")
print("   - Or press Shift+Enter (or Ctrl+Enter) to submit")
print("   - Press Enter alone to add a new line")